name = "hypervision-led"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hypervision-led-db"
database_id = "1d87021d-351f-4701-b80e-bc91305402b2"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "0d99f76205814d69b129dcbf97200ac7"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "8b3a14f7bacb44b7b09b2e1787b040c4"

[[r2_buckets]]
binding = "ASSETS_R2"
bucket_name = "hypervision-led-assets"

[[queues.producers]]
binding = "INQUIRY_QUEUE"
queue = "inquiry-events"

[vars]
CF_ACCESS_AUD = "REPLACE_WITH_ACCESS_AUD"
ADMIN_ALLOWLIST = "admin@hypervision-led.com,editor@hypervision-led.com"
CRM_WEBHOOK_URL = ""
CRM_WEBHOOK_TOKEN = ""
MAIL_WEBHOOK_URL = ""
TURNSTILE_SECRET_KEY = ""
